### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by blessyperumal**
Adding the file highlights places to visit in Bahrain

Closes https://github.com/scatrin/sep-22-developers/issues/2

### CODE REVIEW

**Comment by blessyperumal** [comment]
@scatrin Do you think this is useful?

**Comment by blessyperumal** [comment]
@p-3 :100: Is this ok?

**Comment by blessyperumal** [comment]
@ewallerman Does this look ok?

**Review by katrinsko — CHANGES_REQUESTED** [review]
Are there any good places to get coffee?

**Comment by blessyperumal** [comment]
@scatrin Added a place for coffee. Is it good to :ship: ?

**Review by katrinsko — APPROVED** [review]

**Comment by katrinsko** [comment]
:ship:

**Pull request merged**
